<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01">
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Ad/CCLog.png" width="200" align="center">
</a>

# **Collecting Job Data Using APIs**

Estimated time needed: **45 to 60** minutes

## Objectives

After completing this lab, you will be able to:

*   Collect job data from GitHub Jobs API
*   Store the collected data into an excel spreadsheet.

## Warm-Up Exercise

Before you attempt the actual lab, here is a fully solved warmup exercise that will help you to learn how to access an API.

Using an API, let us find out who currently are on the International Space Station (ISS).<br> The API at [http://api.open-notify.org/astros.json](http://api.open-notify.org/astros.json?utm_medium=Exinfluencer\&utm_source=Exinfluencer\&utm_content=000026UJ\&utm_term=10006555\&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01\&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264\&cm_mmca1=000026UJ\&cm_mmca2=10006555\&cm_mmca3=M12345678\&cvosrc=email.Newsletter.M12345678\&cvo_campaign=000026UJ) gives us the information of astronauts currently on ISS in json format.<br>
You can read more about this API at [http://open-notify.org/Open-Notify-API/People-In-Space/](http://open-notify.org/Open-Notify-API/People-In-Space?utm_medium=Exinfluencer\&utm_source=Exinfluencer\&utm_content=000026UJ\&utm_term=10006555\&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01\&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264\&cm_mmca1=000026UJ\&cm_mmca2=10006555\&cm_mmca3=M12345678\&cvosrc=email.Newsletter.M12345678\&cvo_campaign=000026UJ)

In [ ]:
import requests # you need this module to make an API call

In [ ]:
api_url = "http://api.open-notify.org/astros.json" # this url gives use the astronaut data

In [ ]:
response = requests.get(api_url) # Call the API using the get method and store the
                                # output of the API call in a variable called response.

In [ ]:
if response.ok:             # if all is well() no errors, no network timeouts)
    data = response.json()  # store the result in json format in a variable called data
                            # the variable data is of type dictionary.

In [ ]:
print(data)   # print the data just to check the output or for debugging

{'number': 13, 'message': 'success', 'people': [{'name': 'Mark Vande Hei', 'craft': 'ISS'}, {'name': 'Pyotr Dubrov', 'craft': 'ISS'}, {'name': 'Anton Shkaplerov', 'craft': 'ISS'}, {'name': 'Zhai Zhigang', 'craft': 'Shenzhou 13'}, {'name': 'Wang Yaping', 'craft': 'Shenzhou 13'}, {'name': 'Ye Guangfu', 'craft': 'Shenzhou 13'}, {'name': 'Raja Chari', 'craft': 'ISS'}, {'name': 'Tom Marshburn', 'craft': 'ISS'}, {'name': 'Kayla Barron', 'craft': 'ISS'}, {'name': 'Matthias Maurer', 'craft': 'ISS'}, {'name': 'Oleg Artemyev', 'craft': 'ISS'}, {'name': 'Denis Matveev', 'craft': 'ISS'}, {'name': 'Sergey Korsakov.', 'craft': 'ISS'}]}

Print the number of astronauts currently on ISS.

In [ ]:
print(data.get('number'))

13

Print the names of the astronauts currently on ISS.

In [ ]:
astronauts = data.get('people')
print("There are {} astronauts on ISS".format(len(astronauts)))
print("And their names are :")
for astronaut in astronauts:
    print(astronaut.get('name'))

There are 13 astronauts on ISS
And their names are :
Mark Vande Hei
Pyotr Dubrov
Anton Shkaplerov
Zhai Zhigang
Wang Yaping
Ye Guangfu
Raja Chari
Tom Marshburn
Kayla Barron
Matthias Maurer
Oleg Artemyev
Denis Matveev
Sergey Korsakov.

Hope the warmup was helpful. Good luck with your next lab!

## Lab: Collect Jobs Data using GitHub Jobs API

### Objective: Determine the number of jobs currently open for various technologies

Collect the number of job postings for the following languages using the API:

*   C
*   C#
*   C++
*   Java
*   JavaScript
*   Python
*   Scala
*   Oracle
*   SQL Server
*   MySQL Server
*   PostgreSQL
*   MongoDB

In [ ]:
#Import required libraries
import requests

In [ ]:
baseurl = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/datasets/githubposting.json"

In [ ]:
r=requests.get(baseurl)

In [ ]:
r.headers

{'Date': 'Tue, 29 Mar 2022 13:38:32 GMT', 'X-Clv-Request-Id': '13609a7c-36fa-486a-bcd5-54add2c49037', 'Server': 'Cleversafe', 'X-Clv-S3-Version': '2.5', 'Accept-Ranges': 'bytes', 'x-amz-request-id': '13609a7c-36fa-486a-bcd5-54add2c49037', 'Cache-Control': 'max-age=0,public', 'ETag': '"b02cad792b08e747841c1fb8bb197b7f"', 'Content-Type': 'application/json', 'Last-Modified': 'Fri, 18 Feb 2022 14:07:06 GMT', 'Content-Length': '8984'}

In [ ]:
data = r.json()
data['number of job posting']
technology = []
job_postings = []
for i in range(0,256):
  technology.append(data['technology'][str(i)])

for i in range(0,256):
  job_postings.append(data['number of job posting'][str(i)])

In [ ]:
print(job_postings)

['1', '10', '1', '1', '2', '4', '1', '5', '0', '1', '0', '1', '0', '1', '20', '2', '3', '2', '3', '2', '7', '0', '1', '0', '1', '0', '26', '0', '1', '0', '2', '0', '2', '15', '0', '1', '0', '1', '0', '1', '2', '5', '40', '1', '0', '0', '1', '6', '4', '8', '1', '0', '2', '4', '0', '1', '1', '2', '3', '1', '2', '2', '1', '1', '1', '0', '1', '0', '0', '1', '1', '0', '0', '2', '2', '1', '0', '1', '0', '0', '2', '3', '0', '5', '0', '2', '2', '2', '3', '2', '0', '1', '1', '2', '0', '2', '2', '1', '1', '0', '0', '0', '1', '2', '7', '1', '1', '0', '2', '1', '2', '0', '2', '1', '2', '2', '2', '3', '0', '1', '2', '0', '1', '1', '1', '1', '2', '0', '1', '3', '0', '0', '0', '1', '1', '0', '0', '0', '5', '1', '0', '2', '0', '1', '2', '1', '4', '1', '1', '2', '5', '2', '1', '3', '1', '1', '1', '2', '1', '3', '3', '0', '2', '0', '0', '1', '1', '1', '0', '3', '2', '0', '1', '3', '1', '1', '1', '2', '1', '1', '1', '3', '6', '0', '4', '0', '1', '2', '2', '2', '1', '1', '0', '2', '1', '1', '1', '0', '1', '1', '1', '0', '2', '1', '20', '0', '1', '4', '0', '7', '1', '0', '1', '0', '53', '0', '0', '3', '6', '0', '6', '1', '0', '2', '2', '5', '1', '3', '1', '1', '1', '1', '2', '1', '0', '0', '1', '3', '2', '1', '1', '0', '1', '1', '1', '1', '1', '8', '1', '0', '1', '1', '1', '1', '2', '3']

In [ ]:
import pandas as pd
df=pd.DataFrame({'technology':technology,'job_postings':job_postings})
df.head()

  technology job_postings
0       java            1
1          C           10
2         C#            1
3        C++            1
4       Java            2

In [ ]:
df['job_postings']=df['job_postings'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   technology    256 non-null    object
 1   job_postings  256 non-null    int64
dtypes: int64(1), object(1)
memory usage: 4.1+ KB

In [ ]:
df=df.groupby('technology').job_postings.sum().to_frame()
df.reset_index(inplace=True)
df

      technology  job_postings
0              C           184
1             C#            14
2            C++            24
3           Java            83
4     JavaScript            65
5        MongoDB            18
6   MySQL Server             7
7         Oracle             8
8     PostgreSQL            17
9         Python            51
10    SQL Server            16
11         Scala            47
12          java             9

In [ ]:
def get_number_of_jobs(technology):
    number_of_jobs = df[df['technology']==technology]['job_postings']
    number_of_jobs = int(number_of_jobs.values)
    return technology,number_of_jobs

Call the function for Python and check if it is working.

In [ ]:
print(get_number_of_jobs("Python"))

('Python', 51)

### Store the results in an excel file

Call the API for all the given technologies above and write the results in an excel spreadsheet.

If you do not know how create excel file using python, double click here for **hints**.

<!--

from openpyxl import Workbook        # import Workbook class from module openpyxl
wb=Workbook()                        # create a workbook object
ws=wb.active                         # use the active worksheet
ws.append(['Country','Continent'])   # add a row with two columns 'Country' and 'Continent'
ws.append(['Eygpt','Africa'])        # add a row with two columns 'Egypt' and 'Africa'
ws.append(['India','Asia'])          # add another row
ws.append(['France','Europe'])       # add another row
wb.save("countries.xlsx")            # save the workbook into a file called countries.xlsx


-->

Create a python list of all technologies for which you need to find the number of jobs postings.

In [ ]:
#your code goes here
Technologies = ['C','C#','C++','Java','JavaScript','Python','Scala','Oracle','SQL Server','MySQL Server','PostgreSQL','MongoDB']

Import libraries required to create excel spreadsheet

In [ ]:
# your code goes here
from openpyxl import Workbook

Create a workbook and select the active worksheet

In [ ]:
# your code goes here
wb=Workbook()                        # create a workbook object
ws=wb.active                         #use the active worksheet

Find the number of jobs postings for each of the technology in the above list.
Write the technology name and the number of jobs postings into the excel spreadsheet.

In [ ]:
#your code goes here
for i in Technologies:
    print(get_number_of_jobs(i))

('C', 184)
('C#', 14)
('C++', 24)
('Java', 83)
('JavaScript', 65)
('Python', 51)
('Scala', 47)
('Oracle', 8)
('SQL Server', 16)
('MySQL Server', 7)
('PostgreSQL', 17)
('MongoDB', 18)

In [ ]:
ws.append(['Technology name','Number of jobs'])   
ws.append(['C',184])        
ws.append(['C#',14])         
ws.append(['C++',24])       
ws.append(['Java',92])
ws.append(['JavaScript',65])
ws.append(['Python',51])
ws.append(['Scala',47])
ws.append(['Oracle',6])
ws.append(['SQL Server',16])
ws.append(['MySQL Server',5])
ws.append(['PostgreSQL',17])
ws.append(['MongoDB',4])

Save into an excel spreadsheet named 'github-job-postings.xlsx'.

In [ ]:
#your code goes here
wb.save('github-job-postings.xlsx')

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2021-6-25         | 0.2     | Malika            | Updated GitHub job json link       |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer\&utm_source=Exinfluencer\&utm_content=000026UJ\&utm_term=10006555\&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01\&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264\&cm_mmca1=000026UJ\&cm_mmca2=10006555\&cm_mmca3=M12345678\&cvosrc=email.Newsletter.M12345678\&cvo_campaign=000026UJ).